apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
spec:
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - protocol: TCP
      port: {{ .Values.goService.port }}
      targetPort: {{ .Values.goService.port }}